version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
    - poldixd
    labels:
    - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
